# Generated by Django 5.0.2 on 2024-03-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='USER_IMAGE_URL',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
